#ngninx-pod-secret-volume
apiVersion: v1
kind: Pod
metadata:
  name: ngninx-pod-secret-vol
spec:
  containers:
    -
      image: nginx
      name: nginx-contanier
      volmeMounts:
        -
          mountPath: /etc/confidential
          name: secretmount
          readOnly: true
  volumes:
    -
      name: test-secret-volume
      secret:
        secretName: ngninx-secret-vol
