#redis-pod-secret-env.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-secret-env
spec:
  Containers:
    -
      env:
        -
          name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: redis-secret-env
        -
          name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-secret-env
      image: redis
      name: redis-container
  restartPolicy: Never
